In [2]:
import numpy as np
import pandas as pd

In [2]:
np.zeros_like(np.zeros((3,2)))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.sum(np.exp(np.zeros((3,2))), axis= 1)

array([2., 2., 2.])

In [9]:
np.sum(np.zeros((3,2)) + np.ones((3,2)), axis = 1)

array([2., 2., 2.])

In [7]:
-np.array([[1,1,1],[2,2,2]])[0]

array([-1, -1, -1])

In [3]:
np.argsort(np.zeros((3,2)))

array([[0, 1],
       [0, 1],
       [0, 1]])

In [22]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [26]:
b = np.array([2,2,2])

In [23]:
ind = np.array([[True, False, False],
                [False, True, False],
                [False, False, True]])

In [24]:
a[ind] = a[ind] - 1

In [28]:
a.shape

(3, 3)

In [6]:
a = np.array([[4,4,4,4],
              [6,6,6,6],
              [8,8,8,8]])

b = np.array([2,3,4])

In [7]:
a.shape

(3, 4)

In [8]:
b.shape

(3,)

In [15]:
a / b.reshape((b.shape[0],1))

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [14]:
b.reshape((b.shape[0],1))

array([[2],
       [3],
       [4]])

In [27]:
a / b

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]])

In [25]:
a

array([[0, 2, 3],
       [4, 4, 6],
       [7, 8, 8]])

In [13]:
np.array([1.0,1.0,1.0]) / np.array([2,2,2])

array([0.5, 0.5, 0.5])

Dimension is (Test_count x Train_count)

In [42]:
np.zeros((100, 10))[np.array([1,2,3])]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.random.choice(100, 4)

array([64, 36, 20, 45])

In [38]:
inds = np.arange(5)
np.random.shuffle(inds)
inds[:3]

array([2, 0, 1])

In [ ]:
inds = np.arange(num_train)
            np.random.shuffle(inds)
            inds = inds[:batch_size]

In [4]:
np.log(np.exp(2.6))

2.6

In [7]:
-np.log(0.1)

2.3025850929940455

In [13]:
ab = a.dot(b)

In [15]:
ab[0][2] # 0 - какой объект, 2 - класс

23

In [7]:
np.array([1,2,3],
             dtype=int)

array([1, 2, 3])

In [3]:
a = np.array([[1,2,3],
              [4,3,2]]) # test
b = np.array([[2,3,4],
              [4,3,2],
              [5,5,5]]) # train

b_c = np.array([1,2,1])

In [6]:
a.dot(b)

array([[25, 24, 23],
       [30, 31, 32]])

In [5]:
np.argmax(a.dot(b), axis = 1)

array([0, 2])

In [7]:
np.dot(a, a.T)

array([[14, 16],
       [16, 29]])

In [8]:
np.dot(b, b.T)

array([[29, 25, 45],
       [25, 29, 45],
       [45, 45, 75]])

In [120]:
x, y = a, b

x2 = np.sum(x**2, axis=1, keepdims=True)
y2 = np.sum(y**2, axis=1)
xy = np.dot(x, y.T)
dist = x2 - 2*xy + y2

In [123]:
y2

array([29, 29, 75])

In [122]:
xy

array([[20, 16, 30],
       [25, 29, 45]])

In [113]:
dist

array([[ 3., 11., 29.],
       [ 8.,  0., 14.]])

In [114]:
dist = np.zeros((len(a), len(b)))

for i in range(len(a)):
    for j in range(len(b)):
        dist[i, j] = np.sum(np.square(b[j,:] - a[i,:]))

In [109]:
dist

array([[ 3., 11., 29.],
       [ 8.,  0., 14.]])

In [91]:
a - b[i,:]

array([[-3, -1,  1],
       [ 0,  0,  0]])

In [98]:
np.dot(a, b)

array([[25, 24, 23],
       [30, 31, 32]])

In [95]:
dist_1 = np.zeros((len(a), len(b)))

for i in range(len(a)):
    dist_1[i] = np.sum(np.square(b - a[i, :]), axis=1)

In [96]:
dist_1

array([[ 3., 11., 29.],
       [ 8.,  0., 14.]])

In [97]:
dist

array([[ 3., 11., 29.],
       [ 8.,  0., 14.]])

In [67]:
min_args = []

for i in range(len(a)):
     min_args.append(np.argsort(dist[i])[:3])

In [68]:
min_args[0]

array([0, 1, 2])

In [69]:
list(min_args[0])

[0, 1, 2]

In [70]:
b_c

array([1, 2, 1])

In [71]:
b_c[list(min_args[0])]

array([1, 2, 1])

In [44]:
np.bincount([1,2,3,1,1,11,3])

array([0, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1])

In [45]:
np.argmax(np.bincount([1,2,3,1,1,11,3]))

1

In [47]:
b_c[np.argmax(np.bincount([1,2,3,1,1,11,3]))]

2

In [6]:
a = np.arange(9)
np.random.shuffle(a)
a

array([5, 3, 7, 2, 1, 6, 8, 4, 0])

In [13]:
a = [np.array([1,2,3]), np.array([4,5,6]), np.array([7,8,9])]

In [38]:
for i in range(len(a)):
    print np.concatenate(a[:i] + a[i+1:]), a[i]

[4 5 6 7 8 9] [1 2 3]
[1 2 3 7 8 9] [4 5 6]
[1 2 3 4 5 6] [7 8 9]


In [40]:
a = {1:2}

In [41]:
a[1]

2

In [42]:
np.mean(range(5))

2.0

In [56]:
import datetime

In [79]:
datetime.date('2018-09-03')

TypeError: an integer is required

In [66]:
dt = datetime.datetime(2018,9,3)

In [76]:
dt = datetime.date.today()

In [77]:
int((dt - datetime.date(1970,1,1)).total_seconds())

1535932800

In [80]:
datetime.datetime.strftime('2018-09-03', '%Y-%m-%d')

TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'

In [11]:
np.sum(b, axis=1)

array([3, 6, 9])

In [21]:
a = np.array([[1,2,3],
              [1,1,1]])

b = np.array([[1,1,1],
              [2,2,2],
              [3,3,3]])

In [22]:
b.T

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
np.dot(a, b.T)

array([[ 6, 12, 18],
       [ 3,  6,  9]])

In [49]:
b.T

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
np.sum(a**2, axis=1, keepdims=True)

array([[14],
       [ 3]])

In [55]:
np.sum(a**2, axis=1, keepdims=True) - np.dot(a, b.T)

array([[ 8,  2, -4],
       [ 0, -3, -6]])

In [81]:
import os

In [84]:
os.path.join('a', 'b', '')

'a/b/'

In [97]:
from datetime import date, timedelta, datetime

In [93]:
datetime.datetime(1970,1,1)

datetime.datetime(1970, 1, 1, 0, 0)

In [100]:
datetime.now().date()

datetime.date(2018, 9, 6)

In [142]:
a = np.array([[1, 2, 3],
           [4, 5,-9]])

In [124]:
N = 2
M = 3

test = [[0.0]*M]*N

inverted = [[0.0]*N]*M

print inverted

for j in range(N):
    for i in range(M):
        print i,j, a[j][i], M - i - 1, N - j - 1
        inverted[M - i - 1][N - j - 1] = a[j][i]
        print inverted

print inverted

[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
0 0 1 2 1
[[0.0, 1], [0.0, 1], [0.0, 1]]
1 0 2 1 1
[[0.0, 2], [0.0, 2], [0.0, 2]]
2 0 3 0 1
[[0.0, 3], [0.0, 3], [0.0, 3]]
0 1 4 2 0
[[4, 3], [4, 3], [4, 3]]
1 1 5 1 0
[[5, 3], [5, 3], [5, 3]]
2 1 -9 0 0
[[-9, 3], [-9, 3], [-9, 3]]
[[-9, 3], [-9, 3], [-9, 3]]


In [143]:
a_ = [[0] * M for i in range(N)]
b = [[0] * N for i in range(M)]

In [166]:
# Task1
N = int(input()) 
M = int(input()) 

b = [[0] * N for i in range(M)]

for j in range(N):
    for i in range(M):
        tmp = int(input())
        b[i][N - j - 1] = tmp
        
print '{0} {1}'.format(M, N)
for i in range(M):
    print ' '.join([str(b[i][j]) for j in range(N)])

2
3
1
2
3
4
5
-9
3 2
4 1
5 2
-9 3


In [196]:
# Task2
import re
a = re.findall(r'\d\D', 'asd3kmcsdc0dsc asdc9kca')
b = re.split(r'\d\D', 'asd3kmcsdc0dsc asdc9kca')

s = b[0]
for i in range(len(a)):
    s = s + int(a[i][0])*a[i][1] + b[i + 1]

print s

asdkkkmcsdcsc asdckkkkkkkkkca


In [193]:
# Task3
[1, 2, 3, 4]

['3k', '0d', '9k']

In [5]:
b = np.array([1,2,3,4,5])

In [6]:
b[b > 3] = 0

In [7]:
b

array([1, 2, 3, 0, 0])

In [ ]:
print b[0]

In [130]:
(inverted[0])[1] = 2

In [131]:
inverted

[[-9, 2], [-9, 2], [-9, 2]]

In [112]:
test[0][1] = 3

In [113]:
test

[[0.0, 3, 0.0], [0.0, 3, 0.0]]

In [ ]:
for i in 

In [104]:
a.T

array([[ 1,  4],
       [ 2,  5],
       [ 3, -9]])

In [92]:
timedelta(analyze_time, date(1970,1,1))

TypeError: unsupported type for timedelta seconds component: datetime.date

In [95]:
import time

In [96]:
time.sleep(5)

In [1]:
3.14

3.14

In [2]:
2.09383153 / 3.14

0.6668253280254777